# https://github.com/nodejs/docker-node
# https://nodejs.org/en/docs/guides/nodejs-docker-webapp/
version: "2"
services:
  node:
    image: "node:15"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "8082"
    ports:
      - '8082:3000'
    command: "npm start"
